apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    service: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      service: {{ .Release.Name }}
  template:
    metadata:
      labels:
        service: {{ .Release.Name }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.app.pullSecret }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.app.url }}:{{ .Values.image.app.tag }}"
          imagePullPolicy: {{ .Values.image.app.pullPolicy }}
          env:
            - name: mainnet_contract
              value: {{ .Values.env.mainnet_contract | quote }}
            - name: testnet_contract
              value: {{ .Values.env.testnet_contract | quote }}
            - name: network
              value: {{ .Values.env.network | quote }}

          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
          volumeMounts:
            - name: configmap
              mountPath: /app/.env
              subPath: .env
      volumes:
        - name: configmap
          configMap:
            name: {{ .Release.Name }}-configmap
